stages:
  - build
  - push
  - deploy

variables:
  AWS_REGION: "us-east-1"

build_backend:
  stage: build
  script:
    - docker build -t backend ./app/backend

build_frontend:
  stage: build
  script:
    - docker build -t frontend ./app/frontend

push_backend:
  stage: push
  script:
    - docker tag backend $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/backend
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/backend

push_frontend:
  stage: push
  script:
    - docker tag frontend $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend

deploy:
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no ec2-user@<ec2-ip> 'bash ~/deploy.sh'